services:
    
    beets:
        image: "uroboro89/beets:0.1"
        container_name: "beets"
        network_mode: "host"
        restart: unless-stopped
        volumes:
            - efesto-config:/mnt/efesto-config
            - efesto-data:/mnt/efesto-data
            - efesto-library:/media/music-library
            - efesto-library-org:/media/music

    snapserver:
        image: "uroboro89/snapserver:0.5"
        container_name: "snapserver"
        network_mode: "host"
        restart: unless-stopped
        volumes:
            - efesto-config:/mnt/efesto-config
            - efesto-data:/mnt/efesto-data
            - fifo:/tmp/snapcast/

    mopidy:
        image: "uroboro89/mopidy:0.1"
        container_name: "mopidy"
        network_mode: "host"
        restart: unless-stopped
        volumes:
            - efesto-library-org:/media/music
            - efesto-config:/mnt/efesto-config
            - efesto-data:/mnt/efesto-data
            - fifo:/tmp/snapcast/

volumes:
    fifo:
    efesto-config:
        driver_opts:
            type: nfs
            o: addr=192.168.1.20,ro
            device: :/volume1/music-library/docker/config

    efesto-data:
        driver_opts:
            type: nfs
            o: addr=192.168.1.20,rw
            device: :/volume1/music-library/docker/data

    efesto-library-org:
        driver_opts:
            type: nfs
            o: addr=192.168.1.20,ro
            device: :/volume1/music/

    efesto-library:
        driver_opts:
            type: nfs
            o: addr=192.168.1.20,rw
            device: :/volume1/music-library/